name: Build ctrtool

on:
  push:
    branches: ["main"]

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "3DSGuy/Project_CTR"
    - run: make deps
      working-directory: ctrtool
    - run: make
      working-directory: ctrtool
    - uses: actions/upload-artifact@v4
      with:
        name: ctrtool-linux_amd64
        path: ctrtool/bin/ctrtool

  build-linux-armv7:
    runs-on: ubuntu-latest
    steps:
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: armv7
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          shell: /bin/sh
          dockerRunArgs: |
            -v "${PWD}/artifacts:/artifacts"
          install: |
            apt update -y
            apt install -y build-essential git
          run: |
            mkdir -p /build
            git clone https://github.com/3DSGuy/Project_CTR.git /build
            cd /build/ctrtool
            make deps
            make
            cp bin/ctrtool /artifacts/ctrtool-linux_armv7
          setup: |
            mkdir -p "${PWD}/artifacts"
      - uses: actions/upload-artifact@v4
        with:
          path: artifacts/*

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          shell: /bin/sh
          dockerRunArgs: |
            -v "${PWD}/artifacts:/artifacts"
          install: |
            apt update -y
            apt install -y build-essential git
          run: |
            mkdir -p /build
            git clone https://github.com/3DSGuy/Project_CTR.git /build
            cd /build/ctrtool
            make deps
            make
            cp bin/ctrtool /artifacts/ctrtool-linux_arm64
          setup: |
            mkdir -p "${PWD}/artifacts"
      - uses: actions/upload-artifact@v4
        with:
          path: artifacts/*

  build-macos:
    runs-on: ubuntu-macos
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "3DSGuy/Project_CTR"
      - run: make deps
        working-directory: ctrtool
      - run: make
        working-directory: ctrtool
      - uses: actions/upload-artifact@v4
        with:
          name: ctrtool
          path: ctrtool/bin/ctrtool

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "3DSGuy/Project_CTR"
      - uses: microsoft/setup-msbuild@v2
      - run: msbuild ctrtool/build/visualstudio/CTRTool.sln /p:configuration=Release /p:platform=${{ matrix.platform }} /t:rebuild
      - uses: actions/upload-artifact@v4
        with:
          name: ctrtool-win_${{ matrix.platform }}.exe
          path: ctrtool/build/visualstudio/${{ matrix.platform == 'x64' && 'x64/' || '' }}Release/CTRTool.exe
    strategy:
      matrix:
        platform: [x86, x64]

  release:
    needs:
      - build-linux-amd64
      - build-linux-armv7
      - build-linux-arm64
      - build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            *
