name: Build ctrtool

on:
  push:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: "3DSGuy/Project_CTR"

    - name: Make dependencies
      run: make deps
      working-directory: ./ctrtool

    - name: Make
      run: make
      working-directory: ./ctrtool

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ctrtool
        path: ./ctrtool/bin/ctrtool

  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: "3DSGuy/Project_CTR"

    - uses: microsoft/setup-msbuild@v2
    
    - name: Build
      run: msbuild ./ctrtool/build/visualstudio/CTRTool.sln -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ctrtool
        path: ./ctrtool/bin/ctrtool
